/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppTabBar: typeof import('./src/components/AppTabBar.vue')['default']
    AvatarPicker: typeof import('./src/components/profile/AvatarPicker.vue')['default']
    CaseDirectoryPanel: typeof import('./src/components/chat/CaseDirectoryPanel.vue')['default']
    CasesSubNav: typeof import('./src/components/cases/CasesSubNav.vue')['default']
    CaseUploadDialog: typeof import('./src/components/chat/CaseUploadDialog.vue')['default']
    CaseUploadSheet: typeof import('./src/components/cases/CaseUploadSheet.vue')['default']
    ChatCollapse: typeof import('./src/components/chat/ChatCollapse.vue')['default']
    ChatFileCard: typeof import('./src/components/chat/ChatFileCard.vue')['default']
    ChatMessageBody: typeof import('./src/components/chat/ChatMessageBody.vue')['default']
    ChatSegmentList: typeof import('./src/components/chat/ChatSegmentList.vue')['default']
    EChart: typeof import('./src/components/charts/EChart.vue')['default']
    PageShell: typeof import('./src/components/layout/PageShell.vue')['default']
    PdfJsViewer: typeof import('./src/components/chat/PdfJsViewer.vue')['default']
    PdfPreviewSheet: typeof import('./src/components/common/PdfPreviewSheet.vue')['default']
    ResetPasswordDialog: typeof import('./src/components/profile/ResetPasswordDialog.vue')['default']
    ReviewDirectoryDrawer: typeof import('./src/components/review/ReviewDirectoryDrawer.vue')['default']
    ReviewRoundPanel: typeof import('./src/components/review/ReviewRoundPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollLoadList: typeof import('./src/components/common/ScrollLoadList.vue')['default']
    SubNavSwipeView: typeof import('./src/components/layout/SubNavSwipeView.vue')['default']
    SubNavTabs: typeof import('./src/components/layout/SubNavTabs.vue')['default']
    TabIcon: typeof import('./src/components/TabIcon.vue')['default']
    TaskFormPopup: typeof import('./src/components/tasks/TaskFormPopup.vue')['default']
    TasksSubNav: typeof import('./src/components/tasks/TasksSubNav.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
